### ISSUE TITLE
zigbee

### ISSUE THREAD

**Issue by vizonyc** [cmetz/python-matrixio-hal#2]
Can I talk to the zigbee radio with the hal?

**Comment by cmetz** [comment]
Currently no. the zigbee is controlled via the RPI UART device and is using some default drivers. I have no zigbee environment for testing this stuff, maybe the malos services have some ZMQs allowing to control zigbee with python. When i'am back from my trip to Austria, i'll gonna take a look on it.

**Comment by vizonyc** [comment]
ok let me know what i can provide to help in the end I am trying to get this too work https://github.com/mariusmotea/diyHue or openhab binding for zigbee lights

**Comment by cmetz** [comment]
i have ordered a zigbee bulb and will do some tests with it at weekend.

**Comment by cmetz** [comment]
i played around a littebit with the blub and the matrix zigbee, i could get it working with the provided zigbee gateway. i also tried bellows, but i could not get it working there. i will do some further investigations, maybe bellows could be a solution for a hal python developer.

**Comment by cmetz** [comment]
with a lot of hacking and stracing the ZigBeeGateway (matrix) i got bellows working. now i can control the zigbee bulb directly with python (uart) bypassing the matrix blob. 😀 

https://github.com/zigpy/bellows

**Comment by cmetz** [comment]
I posted an example in the matrix community:

https://community.matrix.one/t/first-zigbee-tests-with-python-bellows-forming-a-network-controller/1579
