### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by gapdev** [cmetz/python-matrixio-hal#4]
Will there be a Python 3 version?

**Comment by cmetz** [comment]
The module should work with both python versions. Do you have any issues running it with python 3?

**Comment by gapdev** [comment]
pip3 won't install it. Seems to hang.

using this:
python3 led_rotate.py

produces this:
Traceback (most recent call last):
  File "led_rotate.py", line 1, in <module>
    from matrixio_hal import everloop
ImportError: No module named 'matrixio_hal'

**Comment by cmetz** [comment]
building the package could take quite a long time, if pip3 needs to install cython. you can try to install cython for python3, that should speedup the build process:
```
sudo apt-get install cython3
```

**Comment by gapdev** [comment]
Works Perfectly, thank you.
